query getFollowingsFromAddress($address: String!) {
  following(args: { address: $address }) {
    id
    image
    label
    type

    triples(order_by: { term_id: desc }) {
      term_id
      creator {
        label
        id
        type
      }
      subject {
        term_id
        label
        image
        type
      }
      predicate {
        term_id
        label
        image
        type
      }
      object {
        term_id
        label
        image
        type
      }
      counter_term_id

      term {
        id
        positions_aggregate {
          aggregate {
            count
          }
        }
        positions(where: { account_id: { _eq: $address } }) { 
          shares
          account {
            id
          }
        }
      }

      counter_term {
        id
        positions_aggregate {
          aggregate {
            count
          }
        }
        positions(where: { account_id: { _eq: $address } }) {
          shares
          account {
            id
          }
        }
      }
    }

    positions_aggregate(limit: 10) {
      aggregate {
        count
      }
      nodes {
        shares
        term {
          id
          triple {
            term
            object {
              term
              type
              image
              label
            }
            predicate {
              term
              type
              image
              label
            }
            subject {
              term
              type
              image
              label
            }
            counter_term {
              id
              positions_aggregate {
                aggregate {
                  count
                }
              }
              positions(where: { account_id: { _eq: $address } }) {
                shares
                account {
                  id
                }
              }
            }
            term {
              id
              positions_aggregate {
                aggregate {
                  count
                }
              }
              positions(where: { account_id: { _eq: $address } }) {
                shares
                account {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
