query GetClaimsByAddress($address: String) {
  claims_aggregate(where: { account_id: { _eq: $address } }) {
    aggregate {
      count
    }
    nodes {
      account {
        label
      }
      triple {
        id
        subject {
          label
          image
          type
        }
        predicate {
          label
          image
          type
        }
        object {
          label
          image
          type
        }
        vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
        counter_vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
      }
      id
      vault_id
      counter_vault_id
      shares
      counter_shares
    }
  }
}

query GetClaimsByAtom($id: numeric) {
  claims_aggregate(where:{ _or: [
      { object_id: { _eq: $id }}
      {subject_id: {_eq: $id}}
    ]
  }
   ) {
    aggregate {
      count
    }
    nodes {
      account {
        label
      }
      triple {
        id
        subject {
          label
          image
          type
        }
        predicate {
          label
          image
          type
        }
      }
    }
  }
}

