query GetClaimsByAddress($address: String) {
  claims_aggregate(where: { account_id: { _eq: $address } }) {
    aggregate {
      count
    }
    nodes {
      account {
        label
      }
      triple {
        id
        subject {
          label
          image
          type
        }
        predicate {
          label
          image
          type
        }
        object {
          label
          image
          type
        }
        vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
        counter_vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
      }
      id
      vault_id
      counter_vault_id
      shares
      counter_shares
    }
  }
}

query GetClaimsByUri($uri: String) {
  atoms(
    where: {
      _or: [
        { data: { _eq: $uri } }
        { value: { thing: { url: { _eq: $uri } } } }
        { value: { person: { url: { _eq: $uri } } } }
        { value: { organization: { url: { _eq: $uri } } } }
        { value: { book: { url: { _eq: $uri } } } }
      ]
    }
  ) {
    as_object_claims_aggregate {
      aggregate {
        count
      }
      nodes {
        id
        predicate {
          label
          image
          type
          id
        }
        subject {
          image
          label
          type
          id
        }
        object {
          label
          image
          type
          id
        }
        vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
        counter_vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
        triple_id
        shares
        counter_shares
      }
    }
    as_subject_claims_aggregate {
      aggregate {
        count
      }
      nodes {
        id
        predicate {
          label
          image
          type
          id
        }
        object {
          label
          image
          type
          id  
        }
        subject {
          label
          image
          type
          id
        }
        vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
        counter_vault {
          positions_aggregate {
            aggregate {
              count
            }
          }
        }
        triple_id
        shares
        counter_shares
      }
    }
    id
    label
    image
    vault {
      position_count
    }
    value {
      thing {
        description
        url
      }
    }
  }
}

query GetClaimsByAtom($id: numeric) {
  claims_aggregate(
    where: { _or: [{ object_id: { _eq: $id } }, { subject_id: { _eq: $id } }] }
  ) {
    aggregate {
      count
    }
    nodes {
      account {
        label
      }
      triple {
        id
        subject {
          label
          image
          type
        }
        predicate {
          label
          image
          type
        }
      }
    }
  }
}
