query getFollowersFromAddress($address: String!) {
  triples(
    where: {
      predicate: { label: { _eq: "follow" } }
      object: { accounts: { id: { _eq: $address } } }
    }
  ) {
    id
    predicate {
      label
    }
    object {
      id
    }

    vault {
      id
      positions {
        shares
        account {
          id
          label
          image
        }
      }
    }

    counter_vault {
      id
      positions {
        shares
        account {
          id
          label
          image
        }
      }
    }
  }
}
