query getFollowingsFromAddress($address: String!) {
  following(args: { address: $address }) {
    id
    image
    label
    type

    triples(order_by: { id: desc }) {
      id
      creator {
        label
        id
        type
      }
      subject {
        id
        label
        image
        type
      }
      predicate {
        id
        label
        image
        type
      }
      object {
        id
        label
        image
        type
      }
      vault_id
      counter_vault_id

      vault {
        id
        positions_aggregate {
          aggregate {
            count
          }
        }
        positions(where: { account_id: { _eq: $address } }) { 
          shares
          account {
            id
          }
        }
      }

      counter_vault {
        id
        positions_aggregate {
          aggregate {
            count
          }
        }
        positions(where: { account_id: { _eq: $address } }) {
          shares
          account {
            id
          }
        }
      }
    }

    positions_aggregate(limit: 10) {
      aggregate {
        count
      }
      nodes {
        shares
        vault {
          id
          triple {
            id
            object {
              id
              type
              image
              label
            }
            predicate {
              id
              type
              image
              label
            }
            subject {
              id
              type
              image
              label
            }
            counter_vault {
              id
              positions_aggregate {
                aggregate {
                  count
                }
              }
              positions(where: { account_id: { _eq: $address } }) {
                shares
                account {
                  id
                }
              }
            }
            vault {
              id
              positions_aggregate {
                aggregate {
                  count
                }
              }
              positions(where: { account_id: { _eq: $address } }) {
                shares
                account {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
