query GetTags($subjectId: numeric!, $predicateId: numeric!) {
  triples(
    where: {
      _and: [
        { subject_id: { _eq: $subjectId } }
        { predicate_id: { _eq: $predicateId } }
      ]
    }
  ) {
    ...TripleMetadata
  }
}

query GetTagsCustom($where: triples_bool_exp) {
  triples(where: $where) {
    ...TripleMetadata
  }
}

query GetTagsObjects($distinctOn: [triples_select_column!], $where: triples_bool_exp, $orderBy: [triples_order_by!]) {
  triples(distinct_on: $distinctOn, where: $where, order_by: $orderBy) {
    object {
      id
      label
      image
      value {
        thing {
          id
          name
          image
          description
          url
        }
        person {
          id
          name
          image
          description
          url
        }
      }
    }
    object_id
  }
}


query GetCountTaggedObjects($objectId: numeric!, $predicateId: numeric!) {
  triples_aggregate(
    where: {
      object_id:    { _eq: $objectId }
      predicate_id: { _eq: $predicateId }
    }
  ) {
    aggregate { count }
  }
}

query GetTaggedObjects(
  $objectId: numeric!
  $predicateId: numeric!
) {
  triples(
    where: {
      object_id:    { _eq: $objectId }
      predicate_id: { _eq: $predicateId }
    }
  ) {
    id
    subject {
      id
      label
      image
      value {
        thing {
          name
          description
          url
        }
        person {
          description
        }
      }
      vault {
        position_count
      }
    }
    vault_id
    vault {
      id
      position_count
        positions {
          shares
        }
    }

    counter_vault {
      id
      position_count
        positions {
          shares
        }
    }
  }
}
