// This file is auto-generated by @hey-api/openapi-ts
export const ClaimSortColumn = {
    VAULT_ID: 'VaultId',
    COUNTER_VAULT_ID: 'CounterVaultId',
    CREATOR: 'Creator',
    SUBJECT_VAULT_ID: 'SubjectVaultId',
    OBJECT_VAULT_ID: 'ObjectVaultId',
    PREDICATE_VAULT_ID: 'PredicateVaultId',
    CREATED_AT: 'CreatedAt',
    UPDATED_AT: 'UpdatedAt',
    STATUS: 'Status',
    NUM_POSITIONS: 'NumPositions',
    FOR_NUM_POSITIONS: 'ForNumPositions',
    AGAINST_NUM_POSITIONS: 'AgainstNumPositions',
    CONVICTION_SUM: 'ConvictionSum',
    FOR_CONVICTION_SUM: 'ForConvictionSum',
    AGAINST_CONVICTION_SUM: 'AgainstConvictionSum',
    ASSETS_SUM: 'AssetsSum',
    FOR_ASSETS_SUM: 'ForAssetsSum',
    AGAINST_ASSETS_SUM: 'AgainstAssetsSum',
    USER_CONVICTION_FOR: 'UserConvictionFor',
    USE_ASSETS_FOR: 'UseAssetsFor',
    USER_CONVICTION_AGAINST: 'UserConvictionAgainst',
    USE_ASSETS_AGAINST: 'UseAssetsAgainst',
    USER_CONVICTION: 'UserConviction',
    USE_ASSETS: 'UseAssets',
};
export const Combinator = {
    AND: 'and',
    OR: 'or',
};
export const EnumComparators = {
    EQ: 'eq',
    NOT_EQ: 'notEq',
};
export const Event = {
    CREATE_ATOM: 'createAtom',
    BATCH_CREATE_ATOM: 'batchCreateAtom',
    CREATE_ATOM_COMPRESSED: 'createAtomCompressed',
    BATCH_CREATE_TRIPLE: 'batchCreateTriple',
    CREATE_TRIPLE: 'createTriple',
    CURRENT_SHARE_PRICE: 'currentSharePrice',
    DEPLOY_ATOM_WALLET: 'deployAtomWallet',
    DEPOSIT_ATOM: 'depositAtom',
    DEPOSIT_TRIPLE: 'depositTriple',
    ENTRY_FEE_AMOUNT: 'entryFeeAmount',
    EXIT_FEE_AMOUNT: 'exitFeeAmount',
    GET_TRIPLE_ATOMS: 'getTripleAtoms',
    GET_VAULT_BALANCE: 'getVaultBalance',
    GET_VAULT_STATE_FOR_USER: 'getVaultStateForUser',
    GET_VAULT_STATES: 'getVaultStates',
    MAX_REDEEM: 'maxRedeem',
    REDEEM_ATOM: 'redeemAtom',
    REDEEM_TRIPLE: 'redeemTriple',
    SET_ADMIN: 'setAdmin',
    SET_ATOM_COST: 'setAtomCost',
};
export const NumericComparators = {
    EQ: 'eq',
    LTE: 'lte',
    LT: 'lt',
    GT: 'gt',
    GTE: 'gte',
    NOT_EQ: 'notEq',
};
export const ParentTable = {
    IDENTITY: 'Identity',
    CLAIM: 'Claim',
};
export const PointType = {
    SOCIAL: 'social',
    QUEST: 'quest',
    REFERRAL: 'referral',
    PROTOCOL: 'protocol',
    NFT: 'nft',
};
export const PositionSortColumn = {
    CREATED_AT: 'CreatedAt',
    UPDATED_AT: 'UpdatedAt',
    CONVICTION: 'Conviction',
    ASSETS: 'Assets',
};
/**
 * This enum represents the conditions that we can handle for quests
 */
export const QuestCondition = {
    ALWAYS_TRUE: 'always_true',
    COUNTER_STAKE_CLAIM: 'counter_stake_claim',
    CREATE_ATOM: 'create_atom',
    CREATE_CLAIM: 'create_claim',
    CREATE_FOLLOW_CLAIM: 'create_follow_claim',
    CREATE_TAG_CLAIM: 'create_tag_claim',
    STAKE_CLAIM: 'stake_claim',
    STAKE_IDENTITY: 'stake_identity',
    UNIMPLEMENTED: 'unimplemented',
};
/**
 * This enum is a direct map to the `quest_narrative` SQL enum. It describes the
 * existing narratives, so every time the SQL enum is updated we need to manually
 * update this enum to keep matching the values
 */
export const QuestNarrative = {
    STANDARD: 'Standard',
    ONBOARDING: 'Onboarding',
    TEST: 'Test',
};
export const QuestSortColumn = {
    CREATED_AT: 'CreatedAt',
    POINTS: 'Points',
    POSITION: 'Position',
};
export const QuestStatus = {
    NOT_STARTED: 'NotStarted',
    STARTED: 'Started',
    COMPLETED: 'Completed',
    WITH_DRAWN: 'WithDrawn',
    CLAIMABLE: 'Claimable',
};
export const Role = {
    USER: 'User',
    ADMIN: 'Admin',
    ATOM: 'Atom',
};
export const SortColumn = {
    IDENTITY_ID: 'IdentityId',
    DISPLAY_NAME: 'DisplayName',
    CREATOR: 'Creator',
    NUM_POSITIONS: 'NumPositions',
    ASSETS_SUM: 'AssetsSum',
    ASSETS_PRICE: 'AssetsPrice',
    DESCRIPTION: 'Description',
    CREATED_AT: 'CreatedAt',
    UPDATED_AT: 'UpdatedAt',
    STATUS: 'Status',
    SHARES_SUM: 'SharesSum',
    CONVICTION_SUM: 'ConvictionSum',
    CONVICTION_PRICE: 'ConvictionPrice',
    ASSET_DELTA: 'AssetDelta',
    CONVICTION_PRICE_DELTA: 'ConvictionPriceDelta',
    USER_CONVICTION: 'UserConviction',
    USER_ASSETS: 'UserAssets',
    USER_ASSET_DELTA: 'UserAssetDelta',
};
export const SortDirection = {
    ASC: 'asc',
    DESC: 'desc',
};
export const Status = {
    PENDING: 'pending',
    COMPLETE: 'complete',
    REMOVED: 'removed',
    ERROR: 'error',
};
export const StatusExplainer = {
    PENDING: 'Pending',
    COMPLETE: 'Complete',
    REMOVED: 'Removed',
};
export const StringComparators = {
    EQ: 'eq',
    CONTAINS: 'contains',
    NOT_EQ: 'notEq',
};
export const TimeFrame = {
    LAST_MINUTE: 'lastMinute',
    LAST5MINUTES: 'last5Minutes',
    LAST10MINUTES: 'last10Minutes',
    LAST_HOUR: 'lastHour',
    LAST4HOURS: 'last4Hours',
    LAST_DAY: 'lastDay',
    LAST_WEEK: 'lastWeek',
    LAST_MONTH: 'lastMonth',
    ANY: 'any',
};
export const UserQuestSortColumn = {
    DATE_STARTED: 'DateStarted',
    DATE_COMPLETED: 'DateCompleted',
    STATUS: 'Status',
    PROGRESS: 'Progress',
    USER_ID: 'UserId',
    QUEST_ID: 'QuestId',
};
export const VaultType = {
    FOR: 'for',
    AGAINST: 'against',
};
export const VecComparators = {
    IN: 'in',
    NOT_IN: 'notIn',
};
