name: Build And Upload Extension Zip Via Artifact

on:
  # Run on PRs to dev, but only when they're opened, synchronized, or reopened
  # (not when they're closed/merged, as that's handled by release.yml)
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline

      - run: pnpm build
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: build/chrome-mv3-prod.zip

      - run: pnpm build:firefox
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: build/firefox-mv2-prod.zip
